#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/ permanent;"
sudo sed -i "42i $new_string" /etc/nginx/sites-available/default

sudo service nginx start
